version: "0.1"

x-mysql-database-config-data:
  &mysql-connection-data
  environment:
    - SPRING_DATASOURCE_PLATFORM=mysql
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=passenger_db

x-postgresql-database-config-data:
  &postgesql-connection-data
  environment:
    - SPRING_DATASOURCE_PLATFORM=postgresql
    - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    - POSTGRES_USER=${POSTGRESQL_USERNAME}
    - POSTGRES_DB=ride_db

x-config-eureka-server:
  &spring-config
  environment:
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka

x-config-passenger-microservice:
  &spring-database-config
  environment:
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka
    - spring.datasource.url=jdbc:mysql://mysqldb:3306/passenger_db

x-config-ride-microservice:
  &spring-postgres-ride-database-config
  environment:
    - spring.datasource.url=jdbc:postgresql://postgresql:5432/ride_db
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka
    - spring.datasource.password=${POSTGRESQL_PASSWORD}
    - spring.datasource.username=${POSTGRESQL_USERNAME}

x-config-driver-microservice:
  &spring-postgres-driver-database-config
  environment:
    - spring.datasource.url=jdbc:postgresql://postgresql:5432/driver_db
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka
    - spring.datasource.password=${POSTGRESQL_PASSWORD}
    - spring.datasource.username=${POSTGRESQL_USERNAME}

x-config-rating-microservice:
  &spring-postgres-rating-database-config
  environment:
    - spring.datasource.url=jdbc:postgresql://postgresql:5432/rating_db
    - eureka.client.service-Url.defaultZone=http://eureka-server:8761/eureka
    - spring.datasource.password=${POSTGRESQL_PASSWORD}
    - spring.datasource.username=${POSTGRESQL_USERNAME}

services:

  mysqldb:
    image: mysql:8.0
    env_file:
      - .env
    restart: always
    ports:
      - 3306:3306
    <<: *mysql-connection-data
    container_name: mysqldb
    networks:
      - app

  postgresql:
    image: postgres:16
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    <<: *postgesql-connection-data
    container_name: postgresql
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - app

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: ./Dockerfile
    image: eurekaserver:latest
    env_file:
      - .env
    ports:
      - 8761:8761
    <<: *spring-config
    container_name: eureka-server
    networks:
      - app

  passenger-service:
    build:
      context: ./passenger-service
      dockerfile: ./Dockerfile
    image: passenger-service
    env_file:
      - .env
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
      - eureka-server
      - kafka
    <<: *spring-database-config
    container_name: passenger_service
    networks:
      - app

  ride-service:
    build:
      context: ../ride-service
      dockerfile: ./Dockerfile
    image: ride-service
    env_file:
      - .env
    ports:
      - 8084:8084
    depends_on:
      - postgresql
      - eureka-server
    <<: *spring-postgres-ride-database-config
    container_name: ride_service
    networks:
      - app

  driver-service:
    build:
      context: ../driver-service
      dockerfile: ./Dockerfile
    image: driver-service
    env_file:
      - .env
    ports:
      - 8082:8082
    depends_on:
      - postgresql
      - eureka-server
      - kafka
    <<: *spring-postgres-driver-database-config
    container_name: driver-service
    networks:
      - app

  rating-service:
    build:
      context: ../rating-service
      dockerfile: ./Dockerfile
    image: rating-service
    env_file:
      - .env
    ports:
      - 8083:8083
    depends_on:
      - postgresql
      - eureka-server
      - kafka
      - ride-service
    <<: *spring-postgres-rating-database-config
    container_name: rating-service
    networks:
      - app

  api-gateway:
    build:
      context: api-gateway
      dockerfile: ./Dockerfile
    image: api-gateway
    <<: *spring-config
    container_name: gateway-service
    networks:
      - app
    depends_on:
      - eureka-server
    ports:
      - 8080:8080

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - app
    restart: always

networks:
  app:
    driver: bridge

volumes:
  kafka_data:
