spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passengers
          uri: lb://passenger-service
          predicates:
            - Path=/passengers/**
        - id: drivers
          uri: lb://driver-service
          predicates:
            - Path=/drivers/**
            - Path=/cars/**
        - id: ratings
          uri: lb://rating-service
          predicates:
            - Path=/ratings/**
          filters:
            - name: CircuitBreaker
              args:
                name: payment-service-circuit
                fallbackUri: forward:/fallback/rating-service
        - id: rides
          uri: lb://ride-service
          predicates:
            - Path=/rides/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 20
        failureRateThreshold: 50
        minimumNumberOfCalls: 20
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 1s
        permittedNumberOfCallsInHalfOpenState: 20
        slidingWindowSize: 20
        slidingWindowType: COUNT_BASED
    instances:
      rating-service-circuit:
        baseConfig: default
