spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: passengers
          uri: lb://Passenger-Service
          predicates:
            - Path=/passengers/**
        - id: drivers
          uri: lb://Driver-Service
          predicates:
            - Path=/drivers/**
            - Path=/cars/**
        - id: ratings
          uri: lb://Rating-Service
          predicates:
            - Path=/ratings/*
        - id: rides
          uri: lb://Ride-Service
          predicates:
            - Path=/rides/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-Url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        eventConsumerBufferSize: 20
        failureRateThreshold: 50
        minimumNumberOfCalls: 20
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 1s
        permittedNumberOfCallsInHalfOpenState: 20
        slidingWindowSize: 20
        slidingWindowType: COUNT_BASED
    instances:
      rating-service-circuit:
        baseConfig: default
