sentinel monitor redis-master-sentinel 127.0.0.1 6379 1
sentinel down-after-milliseconds redis-master-sentinel 5000
sentinel failover-timeout redis-master-sentinel 15000
sentinel parallel-syncs redis-master-sentinel 1
