apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-service
  template:
    metadata:
      labels:
        app: driver-service
    spec:
      containers:
        - name: driver-service
          image: katsiarynakozlova/driver-service:v1.0
          ports:
            - containerPort: 8082
          env:
            - name: eureka.client.service-Url.defaultZone
              value: http://eureka-server:8761/eureka
            - name: spring.datasource.password
              value: persik
            - name: spring.datasource.url
              value: jdbc:postgresql://postgresql:5432/driver_db
            - name: spring.datasource.username
              value: root
