global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'passenger-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['passenger-service:8081']

  - job_name: 'driver-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['driver-service:8082']

  - job_name: 'rating-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['rating-service:8083']

  - job_name: 'ride-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['ride-service:8084']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080']
