apiVersion: v1
kind: Service
metadata:
  labels:
    app: rating-service
  name: rating-service
spec:
  type: ClusterIP
  ports:
    - port: 8083
      targetPort: 8083
  selector:
    app: rating-service
